create table if not exists public.user_dashboard_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  date_label text not null default '',
  title text not null default '',
  subtitle text not null default '',
  impact_cards jsonb not null default '[]'::jsonb,
  current_score integer not null default 0,
  score_delta_text text not null default '',
  map_status text not null default '',
  map_search_placeholder text not null default '',
  map_highlight text not null default '',
  next_dropoff_label text not null default '',
  next_dropoff_value text not null default '',
  weekly_score_series jsonb not null default '[]'::jsonb,
  weekly_score_note text not null default '',
  emission_series jsonb not null default '[]'::jsonb,
  emission_note text not null default '',
  donut_metrics jsonb not null default '[]'::jsonb,
  league_name text not null default '',
  next_rank_text text not null default '',
  quick_actions_title text not null default '',
  quick_actions jsonb not null default '[]'::jsonb,
  ai_tiles jsonb not null default '[]'::jsonb,
  focus_tasks jsonb not null default '[]'::jsonb,
  weekly_breakdown jsonb not null default '[]'::jsonb,
  carbon_snapshot text not null default '',
  ecocoach_message text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dashboard_leaderboard (
  id bigint generated by default as identity primary key,
  rank integer not null unique,
  display_name text not null,
  role_label text not null default '',
  score integer not null default 0,
  avatar_url text,
  is_featured boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_goals_content (
  user_id uuid primary key references auth.users(id) on delete cascade,
  title text not null default '',
  subtitle text not null default '',
  quick_actions jsonb not null default '[]'::jsonb,
  focus_areas jsonb not null default '[]'::jsonb,
  current_streak text not null default '',
  badges_unlocked text not null default '',
  upcoming_challenge text not null default '',
  nudges jsonb not null default '[]'::jsonb,
  goal_health text not null default '',
  rewards_queue text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_scan_content (
  user_id uuid primary key references auth.users(id) on delete cascade,
  title text not null default '',
  subtitle text not null default '',
  instant_guidance_title text not null default '',
  instant_guidance_subtitle text not null default '',
  action_buttons jsonb not null default '[]'::jsonb,
  camera_title text not null default '',
  camera_subtitle text not null default '',
  camera_status text not null default '',
  ai_waste_items jsonb not null default '[]'::jsonb,
  barcode_items jsonb not null default '[]'::jsonb,
  recent_scans_summary text not null default '',
  ecocoach_tip text not null default '',
  rewards_text text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.scan_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_label text not null default '',
  title text not null default '',
  details text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_profile_content (
  user_id uuid primary key references auth.users(id) on delete cascade,
  title text not null default '',
  subtitle text not null default '',
  quick_actions jsonb not null default '[]'::jsonb,
  personal_profile_items jsonb not null default '[]'::jsonb,
  connected_accounts text not null default '',
  community_rank text not null default '',
  support_text text not null default '',
  account_controls jsonb not null default '[]'::jsonb,
  persona_text text not null default '',
  support_status text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_dashboard_leaderboard_rank
on public.dashboard_leaderboard(rank);

create index if not exists idx_scan_events_user_created
on public.scan_events(user_id, created_at desc);

drop trigger if exists trg_user_dashboard_stats_updated_at on public.user_dashboard_stats;
create trigger trg_user_dashboard_stats_updated_at
before update on public.user_dashboard_stats
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_goals_content_updated_at on public.user_goals_content;
create trigger trg_user_goals_content_updated_at
before update on public.user_goals_content
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_scan_content_updated_at on public.user_scan_content;
create trigger trg_user_scan_content_updated_at
before update on public.user_scan_content
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_profile_content_updated_at on public.user_profile_content;
create trigger trg_user_profile_content_updated_at
before update on public.user_profile_content
for each row
execute function public.set_updated_at();

alter table public.user_dashboard_stats enable row level security;
alter table public.dashboard_leaderboard enable row level security;
alter table public.user_goals_content enable row level security;
alter table public.user_scan_content enable row level security;
alter table public.scan_events enable row level security;
alter table public.user_profile_content enable row level security;

drop policy if exists "user_dashboard_stats_select_own_or_admin" on public.user_dashboard_stats;
create policy "user_dashboard_stats_select_own_or_admin"
on public.user_dashboard_stats
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_dashboard_stats_insert_own_or_admin" on public.user_dashboard_stats;
create policy "user_dashboard_stats_insert_own_or_admin"
on public.user_dashboard_stats
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_dashboard_stats_update_own_or_admin" on public.user_dashboard_stats;
create policy "user_dashboard_stats_update_own_or_admin"
on public.user_dashboard_stats
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "dashboard_leaderboard_select_authenticated" on public.dashboard_leaderboard;
create policy "dashboard_leaderboard_select_authenticated"
on public.dashboard_leaderboard
for select
to authenticated
using (true);

drop policy if exists "dashboard_leaderboard_manage_admin" on public.dashboard_leaderboard;
create policy "dashboard_leaderboard_manage_admin"
on public.dashboard_leaderboard
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "user_goals_content_select_own_or_admin" on public.user_goals_content;
create policy "user_goals_content_select_own_or_admin"
on public.user_goals_content
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_goals_content_insert_own_or_admin" on public.user_goals_content;
create policy "user_goals_content_insert_own_or_admin"
on public.user_goals_content
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_goals_content_update_own_or_admin" on public.user_goals_content;
create policy "user_goals_content_update_own_or_admin"
on public.user_goals_content
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_scan_content_select_own_or_admin" on public.user_scan_content;
create policy "user_scan_content_select_own_or_admin"
on public.user_scan_content
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_scan_content_insert_own_or_admin" on public.user_scan_content;
create policy "user_scan_content_insert_own_or_admin"
on public.user_scan_content
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_scan_content_update_own_or_admin" on public.user_scan_content;
create policy "user_scan_content_update_own_or_admin"
on public.user_scan_content
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "scan_events_select_own_or_admin" on public.scan_events;
create policy "scan_events_select_own_or_admin"
on public.scan_events
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "scan_events_insert_own_or_admin" on public.scan_events;
create policy "scan_events_insert_own_or_admin"
on public.scan_events
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "scan_events_update_own_or_admin" on public.scan_events;
create policy "scan_events_update_own_or_admin"
on public.scan_events
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "scan_events_delete_own_or_admin" on public.scan_events;
create policy "scan_events_delete_own_or_admin"
on public.scan_events
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_profile_content_select_own_or_admin" on public.user_profile_content;
create policy "user_profile_content_select_own_or_admin"
on public.user_profile_content
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_profile_content_insert_own_or_admin" on public.user_profile_content;
create policy "user_profile_content_insert_own_or_admin"
on public.user_profile_content
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "user_profile_content_update_own_or_admin" on public.user_profile_content;
create policy "user_profile_content_update_own_or_admin"
on public.user_profile_content
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());
