create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default 'EcoTracker User',
  role text not null default 'user' check (role in ('user', 'admin')),
  city text not null default 'Lyon, France',
  preferred_mode text not null default 'Bike + Transit',
  primary_goal text not null default 'Low-waste kitchen',
  points integer not null default 2450,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  page text not null,
  task_id text not null,
  completed boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, page, task_id)
);

create table if not exists public.market_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  points integer not null check (points > 0),
  description text not null,
  image text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.market_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.market_products(id),
  points_spent integer not null check (points_spent > 0),
  created_at timestamptz not null default timezone('utc', now())
);
